"""empty message

Revision ID: f5baf54842cb
Revises: 
Create Date: 2022-02-09 14:27:00.545744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5baf54842cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_signin_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=90), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=False),
    sa.Column('password', sa.String(length=90), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_signin_info')
    # ### end Alembic commands ###
